{
 "title": "Farm-proxy",
 "tags": [ "farm-proxy" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "algorithm", "label": "algo", "query": { "query": "label_values(algorithm)" } },
   {
    "name": "route_name",
    "label": "config",
    "query": {
     "query": "label_values({algorithm=~\"$algorithm\"},name)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "label_values({name=~\"$route_name\"},port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hashrate",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hr_1min_total{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1m])) by (instance)",
     "legendFormat": "Upstream"
    },
    {
     "expr": "sum(avg_over_time(hr_1min_total{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1m])) by (instance)",
     "legendFormat": "Downstream"
    }
   ]
  },
  {
   "title": "Hashrate ratio",
   "type": "stat",
   "description": "Upstream/downstream ratio for the selected dashboard period",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hr_1min_total{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[$__range])) by (instance) / sum(avg_over_time(hr_1min_total{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[$__range])) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Aggregation",
   "type": "stat",
   "description": "Aggregation ratio",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conn_count {algorithm=\"$algorithm\", name=~\"$route_name\",stream=\"downstream\" }) / sum(conn_count{algorithm=\"$algorithm\", name=~\"$route_name\",stream=\"upstream\" })",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "release", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time of operation without reboot",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "uptime_secs", "legendFormat": " " }
   ]
  },
  {
   "title": "Server info",
   "type": "bargauge",
   "description": "CPU, memory, disk",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by(job) (irate(node_cpu_seconds_total{job=~\"node-exporter\", mode!=\"idle\"}[30s])) / on(job) group_left sum by (job)((irate(node_cpu_seconds_total{job=~\"node-exporter\"}[30s])))) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "((node_memory_MemTotal_bytes{job=~\"node-exporter\"} - node_memory_MemAvailable_bytes{job=~\"node-exporter\"}) / node_memory_MemTotal_bytes{job=~\"node-exporter\"}) * 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=~\"node-exporter\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",job=~\"node-exporter\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=~\"node-exporter\"} * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conn_count {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\" })",
     "legendFormat": "Upstream connection count"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conn_count {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\" })",
     "legendFormat": "Downstream connection count"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "timeseries",
   "description": "Hashrate forwarded to target pool(s)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hr_1min{stream=\"upstream\", source=\"main\", algorithm=\"$algorithm\", name=~\"$route_name\"}[15s])) by (instance)",
     "legendFormat": "HR 5m"
    },
    {
     "expr": "sum(avg_over_time(hr_1min{stream=\"upstream\", source=\"fallback\", algorithm=\"$algorithm\", name=~\"$route_name\"}[15s])) by (instance)",
     "legendFormat": "HR 5m, fallback"
    },
    {
     "expr": "sum(avg_over_time(hr_1min_total{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1h])) by (instance)",
     "legendFormat": "HR 1h"
    },
    {
     "expr": "sum(avg_over_time(hr_1min_total{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1d])) by (instance)",
     "legendFormat": "HR 1d"
    }
   ]
  },
  {
   "title": "Downstream hashrate",
   "type": "timeseries",
   "description": "Hashrate received from miners",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hr_1min{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[5m])) by (instance)",
     "legendFormat": "HR 5m"
    },
    {
     "expr": "sum(avg_over_time(hr_1min{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1h])) by (instance)",
     "legendFormat": "HR 1h"
    },
    {
     "expr": "sum(avg_over_time(hr_1min{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[1d])) by (instance)",
     "legendFormat": "HR 1d"
    }
   ]
  },
  {
   "title": "Upstream shares",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(accepted {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rejected {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sum(stale {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Stale"
    }
   ]
  },
  {
   "title": "Downstream shares",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(accepted {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rejected {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sum(stale {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) / (sum(accepted{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(rejected{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}) + sum(stale{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}))",
     "legendFormat": "Stale"
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream connections",
     "type": "timeseries",
     "description": "Connections to target pool(s)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(conn_count {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\" })",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downstream connections",
     "type": "timeseries",
     "description": "Connections from miners",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(conn_count {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\" })",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream shares",
     "type": "timeseries",
     "description": "Shares forwarded to target pool(s)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(delta(accepted{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(delta(rejected{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "rejected"
      },
      {
       "expr": "sum(delta(stale{stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "stale"
      }
     ]
    },
    {
     "title": "Downstream shares",
     "type": "timeseries",
     "description": "Shares received from miners",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(delta(accepted{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(delta(rejected{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "rejected"
      },
      {
       "expr": "sum(delta(stale{stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\"}[20s]))",
       "legendFormat": "stale"
      }
     ]
    },
    {
     "title": "Upstream difficulty",
     "type": "timeseries",
     "description": "Average mining difficulty set by target pool(s)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_diff {stream=\"upstream\", algorithm=\"$algorithm\", name=~\"$route_name\" }",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Downstream difficulty",
     "type": "timeseries",
     "description": "Average mining difficulty set to miners",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_diff {stream=\"downstream\", algorithm=\"$algorithm\", name=~\"$route_name\" }",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Legend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "All available configurations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      { "expr": "conn_count", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}