name: 'proxy'

networks:
  hashcore-proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.12.0/24

volumes:
  prometheus_data: {}
  grafana_data: {}
  proxy_configs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      # /!\ To be modified depending on your needs /!\ if you use windows, you need change ./configs to .\configs
      device: "./configs"

services:
  # Metrics Storage
  prometheus:
    image: prom/prometheus
    container_name: hashcore-prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=14d'

    depends_on:
      - node-exporter
    networks:
      - hashcore-proxy

  # metrics exporter
  node-exporter:
    image: prom/node-exporter
    container_name: hashcore-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

    restart: always
    deploy:
      mode: global
    networks:
      - hashcore-proxy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: hashcore-cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hashcore-proxy

  # Charts for Metrics
  grafana:
    image: grafana/grafana
    container_name: hashcore-grafana
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/public/img/fav32.png:/usr/share/grafana/public/img/fav32.png
      - ./monitoring/grafana/public/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg

    env_file:
      - ./monitoring/grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - stratum-proxy
    networks:
      - hashcore-proxy

  # Stratum Proxy
  stratum-proxy:
    image: ${PROXY_REPOSITORY:-public.ecr.aws/k7t2c2k4/farm-proxy}:${PROXY_ENV:-latest}
    container_name: hashcore-stratum-proxy
    restart: always
    volumes:
      - proxy_configs:/opt/stratum-proxy/configs
    ports:
      - "4050:4050"
    networks:
      - hashcore-proxy

  # Proxy Configurator
  proxy-configurator:
    image: ${CONFIGURATOR_REPOSITORY:-public.ecr.aws/k7t2c2k4/stratum-proxy-configurator}:${CONFIGURATOR_ENV:-latest}
    container_name: hashcore-proxy-configurator
    restart: always
    ports:
      - "6034:6034"
    volumes:
      - proxy_configs:/opt/config_agent/configs
      - ./docker-compose.yml:/opt/config_agent/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hashcore-proxy
    depends_on:
      - stratum-proxy