version: '3.8'
name: 'proxy'

networks:
  hashcore-proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.12.0/24

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: hashcore-prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=14d'
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
    networks:
      - hashcore-proxy

  node-exporter:
    image: prom/node-exporter
    container_name: hascore-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
    networks:
      - hashcore-proxy

  grafana:
    image: grafana/grafana
    container_name: hascore-grafana
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/public/img/fav32.png:/usr/share/grafana/public/img/fav32.png
      - ./monitoring/grafana/public/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg

    env_file:
      - ./monitoring/grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - farm-proxy
    networks:
      - hashcore-proxy

  farm-proxy:
    image: public.ecr.aws/k7t2c2k4/farm-proxy:${ENV:-stg}
    container_name: hashcore-farm-proxy
    restart: always
    volumes:
    # /!\ To be modified depending on your needs /!\ if you use windows, you need change ./configs to .\configs
      - ./configs:/opt/farm-proxy/configs
    ports:
      - "4042:4042"
      - "4043:4043"
      - "4050:4050"
    networks:
      - hashcore-proxy