# Login/Password pairs are used for authorization on the configurator
credentials:
  username: admin
  password: admin
# Secret key for JWT token generation. Configurator use this value on the backend side
jwt:
  secret: random_value
