log_level: info
bind_api_addr: 0.0.0.0:4050
log_dir: "./configs/log"
ports:
  - bind_port: 3333               # Mining port
    name: "via-btc"               # Name for grafana
    submission_rate: 0.2          # Number of shares per second. Default 0.2 (1 share / 5 seconds = 0.2)
    aggregation: 255              # Number of connected miners per connection to the pool (default 255, range from 1 to 256)
    mining_algorithm: sha256d     # Selected port algorithm (sha256d / scrypt)
    pools:
      - url: btc.viabtc.io:3333   # Stratum URL
        user: login1              # Pools login (mining name)
        pass: x                   # Password (123 or x)
      - url: btc.viabtc.io:443    # Stratum URL
        user: login1              # Pools login (mining name)
        pass: x                   # Password (123 or x)
  - bind_port: 3434               # Mining port
    name: "via-ltc"               # Name for grafana
    submission_rate: 0.2          # Number of shares per second. Default 0.2 (1 share / 5 seconds = 0.2)
    aggregation: 255              # Number of connected miners per connection to the pool (default 255, range from 1 to 256)
    mining_algorithm: scrypt      # Selected port algorithm (sha256d / scrypt)
    pools:
      - url: ltc.viabtc.io:3333   # Stratum URL
        user: login1              # Pools login (mining name)
        pass: 123                 # Password (123 or x)